language: go
go:
  - 1.8.x
  - 1.9.x

branches:
  only:
  - master

script: 
  - make setup_development
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash) -t d8e90480-715d-40b9-a740-de82e12ad705